on:
  workflow_dispatch:
    inputs:
      resource:
        description: Resource to be managed by the service
        default: thing
        required: true
      proto_file:
        description: Location of the proto file
        default: ./proto/com/acme/schema/v1/thing.proto
        required: true
      proto_service:
        description: gRPC service name within the proto file
        default: ThingService
        required: true

permissions:
  contents: write

name: Cookiecutter

jobs:
  make:
    name: Make a cookie
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - run: pip install -r requirements.txt
      - run: |
          set -e
          cookiecutter . \
          --no-input \
          --output-dir ./cookie \
          $(printf '%s ' \
            "project_owner=${{ github.repository_owner }}" \
            "project_name=${{ github.event.repository.name }}" \
            "resource=${{ github.event.inputs.resource }}" \
            "proto_file=${{ github.event.inputs.proto_file }}" \
            "proto_service=${{ github.event.inputs.proto_service }}"
          )
      - run: |
          echo "PROJECT_FOLDER=$(ls -d ./cookie/* | head -n 1)" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v4
        with:
          name: cookie
          include-hidden-files: true
          path: ${{ env.PROJECT_FOLDER }}/**
  bake:
    needs: make
    name: Bake the cookie
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: cookie
      - name: Reinitialize git repository
        shell: bash
        run: |
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config --global user.name "$GITHUB_ACTOR"
          git init
          git add .
          git commit -m "Initialized from cookiecutter"
          git branch -M main
          git remote add origin https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}.git
          git push -u -f origin main
